### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [Trond240/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [ ] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by damwhit** [comment]
Hey Trond,

This is close in many ways, however there are a few things that we'd like for you to fix. Your class names and instances make a lot of sense, however there are some details we'd like you to address.

* [x] Fix the format of the top-down-design file. 
  * We would like it to be nested/indented and formatted like the way we did in session 5. You can change the file extension to .txt if that helps
* [x] Make sure that your methods use attributes you've listed.
  * ie. calculate_capacity (subtracts current_capacity by total_capacity) - this method is great, but make sure that those attributes have also been listed.
* [x] Make sure that your methods either reassign or calculate return values based on the attribute values you've provided.
* [x] Make sure your commit messages indicate the changes you make
  * Your commit messages after "Initial Commit" should provide context for what you're doing in the commit. So instead of "Sixth Commit", "Add class 2 example object" would have been more appropriate. 

Don't hesitate to reach out with any questions!

**Comment by damwhit** [comment]
@Trond240 this is a ton closer. We'll go ahead an promote you to `technical ready`, however I wanted to let you know that the weakest part of the assessment was your performance on the OOP portion. I want you to think about the following questions when defining methods in the future: 

* Does my method either calculate something based on multiple attributes' values or reassign an attribute's value?
* Does my method fall under the `encapsulation` of the the class I'm defining?
* Does my method require iteration? Am I using the right data type, and am I defining it correctly?
